import os
import requests

# Lista de URLs de imágenes
urls = [
"https://world.digimoncard.com/images/common/header/img_logo.png?v=2",
"https://world.digimoncard.com/images/common/gnavi/sp/nav_global.png",
"https://world.digimoncard.com/images/common/header/img_logo.png?v=2",
"https://world.digimoncard.com/images/common/gnavi/gnavi_about.png?v02",
"https://world.digimoncard.com/images/common/gnavi/gnavi_rule.png?v02",
"https://world.digimoncard.com/images/common/gnavi/gnavi_products.png",
"https://world.digimoncard.com/images/common/gnavi/gnavi_news.png",
"https://world.digimoncard.com/images/common/gnavi/gnavi_event.png?v02",
"https://world.digimoncard.com/images/common/gnavi/gnavi_cardlist.png?v02",
"https://world.digimoncard.com/images/common/gnavi/gnavi_liberator.png",
"https://world.digimoncard.com/images/common/ico_twitter.png",
"https://world.digimoncard.com/images/common/ico_fb.png",
"https://world.digimoncard.com/images/common/ico_ig.png",
"https://world.digimoncard.com/images/common/ico_mv.png",
"https://world.digimoncard.com/images/common/gnavi/sp/btn_close.png",
"https://world.digimoncard.com/images/common/header/pc/nav_global.png",
"https://world.digimoncard.com/images/common/header/img_logo.png?v=2",
"https://world.digimoncard.com/images/common/header/logo_liberator.png",
"https://world.digimoncard.com/images/common/ico_twitter.png",
"https://world.digimoncard.com/images/common/ico_fb.png",
"https://world.digimoncard.com/images/common/ico_ig.png",
"https://world.digimoncard.com/images/common/ico_mv.png",
"https://world.digimoncard.com/images/products/deck/st-20/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/deck/st-21/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/pack/ver21/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/pack/ex-09/bnr.jpg?250418",
"https://world.digimoncard.com/images/top/bnr/bnr_digimon-liberator.jpg?240531",
"https://world.digimoncard.com/images/top/bnr/bnr_digimon-liberator.jpg?240531",
"https://world.digimoncard.com/images/products/deck/st-20/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/deck/st-21/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/pack/ver21/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/pack/ex-09/bnr.jpg?250418",
"https://world.digimoncard.com/images/top/bnr/bnr_digimon-liberator.jpg?240531",
"https://world.digimoncard.com/images/products/deck/st-20/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/deck/st-21/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/pack/ver21/bnr.jpg?250214",
"https://world.digimoncard.com/images/products/pack/ex-09/bnr.jpg?250418",
"https://world.digimoncard.com/images/top/bnr/bnr_digimon-liberator.jpg?240531",
"https://world.digimoncard.com/images/top/flbnr_close.png",
"https://world.digimoncard.com/images/top/bnr/flbnr_liberator_sp.png",
"https://world.digimoncard.com/images/common/tit_pickup.png",
"https://world.digimoncard.com/images/top/pickup_pluginmanual.png",
"https://world.digimoncard.com/images/products/pack/ver21/thumb_enq.png",
"https://world.digimoncard.com/images/products/deck/st20-21/thumb_enq.png",
"https://world.digimoncard.com/images/products/pack/ver19-20/thumb_enq.png",
"https://world.digimoncard.com/images/common/tit_videos.png",
"https://world.digimoncard.com/images/common/tit_topics.png",
"https://world.digimoncard.com/images/top/frame/icon_l.png",
"https://world.digimoncard.com/images/top/btn_topics_all.png",
"https://world.digimoncard.com/images/top/btn_topics_news.png",
"https://world.digimoncard.com/images/top/btn_topics_cardlist.png?v2",
"https://world.digimoncard.com/images/top/btn_topics_rule.png?v2",
"https://world.digimoncard.com/images/top/btn_topics_event.png?v2",
"https://world.digimoncard.com/images/top/btn_topics_products.png",
"https://world.digimoncard.com/images/top/frame/icon_r.png",
"https://world.digimoncard.com/images/event/2025/release-event/03/thumb.png",
"https://world.digimoncard.com/images/event/2025/ultimate_cup/season2/thumb.png",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/event/2025/regionals/season2/thumb.png",
"https://world.digimoncard.com/images/event/2025/gen-con/thumb.png",
"https://world.digimoncard.com/images/event/2025/regionals/season1/thumb.png",
"https://world.digimoncard.com/images/event/2025/ultimate_cup/season1/thumb.png",
"https://world.digimoncard.com/images/event/2025/regionals/season1/thumb.png",
"https://world.digimoncard.com/images/cardlist/thmb/522901_250502.png",
"https://world.digimoncard.com/images/event/2025/store_tournament/03/thumb.png",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/products/pack/ver21/thumb_enq.png",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/event/2025/evolution-cup/01/thumb.png",
"https://world.digimoncard.com/images/event/2025/ultimate_cup/season1/thumb.png",
"https://world.digimoncard.com/images/products/goods/sleeve_11/thumb.png",
"https://world.digimoncard.com/images/products/deck/st20-21/thumb_enq.png",
"https://world.digimoncard.com/images/products/pack/ex-09/thumb.png?v2",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/cardlist/thmb/522901_250411.png",
"https://world.digimoncard.com/images/news/new-store-decorations02/thumb.png",
"https://world.digimoncard.com/images/event/2025/regionals/season1/thumb.png",
"https://world.digimoncard.com/images/news/p-letter_vol2/thumb.png",
"https://world.digimoncard.com/images/products/goods/tamers-evolution-box/thumb.png",
"https://world.digimoncard.com/images/cardlist/thmb/522901_250404_1.png",
"https://world.digimoncard.com/images/cardlist/thmb/522901_250404_2.png",
"https://world.digimoncard.com/images/cardlist/thmb/522901_250404_3.png",
"https://world.digimoncard.com/images/cardlist/thmb/522901_250404_4.png",
"https://world.digimoncard.com/images/cardlist/thmb/522028.png",
"https://world.digimoncard.com/images/cardlist/thmb/522120.png",
"https://world.digimoncard.com/images/cardlist/thmb/522121.png",
"https://world.digimoncard.com/images/products/deck/st20-21/thumb.png",
"https://world.digimoncard.com/images/products/pack/ver21/thumb.png",
"https://world.digimoncard.com/images/rule/thmb/01.png",
"https://world.digimoncard.com/images/top/btn_more.png",
"https://world.digimoncard.com/images/top/btn_topics_close.png",
"https://world.digimoncard.com/images/common/ico_twitter.png?240524",
"https://world.digimoncard.com/images/common/ico_fb.png?240524",
"https://world.digimoncard.com/images/common/ico_ig.png?240524",
"https://world.digimoncard.com/images/common/ico_mv.png?240524",
"https://world.digimoncard.com/images/common/footer/logo_bcg.png",
"https://world.digimoncard.com/images/common/footer/logo_tcg.png",
"https://world.digimoncard.com/images/common/footer/logo_bandai.png",
"https://world.digimoncard.com/images/common/footer/logo_bandai_namco.png",
]

# Crear carpeta si no existe
carpeta = "imagenes_digimon"
os.makedirs(carpeta, exist_ok=True)

# Descargar imágenes
for i, url in enumerate(urls, start=1):
    try:
        response = requests.get(url)
        response.raise_for_status()
        extension = url.split('.')[-1].split('?')[0]  # obtiene png o jpg
        nombre_archivo = os.path.join(carpeta, f"imagen_{i}.{extension}")
        with open(nombre_archivo, 'wb') as f:
            f.write(response.content)
        print(f"✅ Imagen {i} descargada: {nombre_archivo}")
    except Exception as e:
        print(f"❌ Error al descargar imagen {i} ({url}): {e}")
